[package]
name = "omni-led-new-setup"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
mlua = { version = "0.11", features = ["lua54", "vendored", "macros"] }
omni-led = { version = "0.4.1", path = "../omni-led" }
rusb = "0.9"
log = "0.4.22"
